// Word lists for every game.

export const categories = [
  { id: 'animals', name: 'Animals', emoji: '🦁', words: [
    'Elephant', 'Giraffe', 'Penguin', 'Kangaroo', 'Octopus', 'Flamingo', 'Sloth', 'Shark',
    'Chameleon', 'Peacock', 'Hedgehog', 'Gorilla', 'Dolphin', 'Koala', 'Crocodile', 'Owl',
    'Squirrel', 'Zebra', 'Jellyfish', 'Lobster', 'Camel', 'Panda', 'Bat', 'Snail',
    'Horse', 'Chicken', 'Frog', 'Spider', 'Seal', 'Polar Bear',
  ] },
  { id: 'food', name: 'Food & Drink', emoji: '🍕', words: [
    'Pizza', 'Sushi', 'Tacos', 'Spaghetti', 'Pancakes', 'Burrito', 'Popcorn', 'Ice Cream',
    'Croissant', 'Hot Dog', 'Avocado', 'Birthday Cake', 'Ramen', 'Cheeseburger', 'Fries', 'Waffles',
    'Donut', 'Lasagna', 'Pineapple', 'Watermelon', 'Fondue', 'Curry', 'Bagel', 'Nachos',
    'Smoothie', 'Coffee', 'Lemonade', 'Marshmallow', 'Pretzel', 'Omelette',
  ] },
  { id: 'movies', name: 'Movies & TV', emoji: '🎬', words: [
    'Titanic', 'Jurassic Park', 'Harry Potter', 'The Lion King', 'Star Wars', 'Frozen', 'Jaws', 'Shrek',
    'Home Alone', 'The Matrix', 'Finding Nemo', 'Toy Story', 'Barbie', 'Friends', 'The Office', 'Stranger Things',
    'Game of Thrones', 'Breaking Bad', 'Mean Girls', 'Top Gun', 'Rocky', 'Ghostbusters', 'Back to the Future', 'The Godfather',
    'Spider-Man', 'Mamma Mia!', 'Grease', 'Squid Game', 'The Simpsons', 'Pirates of the Caribbean',
    'Avatar', 'Inception', 'Gladiator', 'Up', 'Coco', 'Moana', 'Aladdin', 'Bluey', 'Seinfeld', 'Twilight', 'Alien', 'Cars',
  ] },
  { id: 'places', name: 'Places', emoji: '📍', words: [
    'Airplane', 'Beach', 'Hospital', 'Casino', 'Movie Theater', 'Submarine', 'Space Station', 'School',
    'Zoo', 'Pirate Ship', 'Bank', 'Circus', 'Supermarket', 'Wedding', 'Gym', 'Library',
    'Nightclub', 'Restaurant', 'Police Station', 'Ski Resort', 'Hotel', 'Train', 'Museum', 'Farm',
    'Cruise Ship', 'Haunted House', "Dentist's Office", 'Airport', 'Campsite', 'Theme Park',
  ] },
  { id: 'jobs', name: 'Jobs', emoji: '👩‍🚒', words: [
    'Firefighter', 'Astronaut', 'Chef', 'Dentist', 'Pilot', 'Teacher', 'Magician', 'Plumber',
    'Lifeguard', 'Detective', 'Surgeon', 'DJ', 'Farmer', 'Barber', 'Mail Carrier', 'Zookeeper',
    'Lawyer', 'Photographer', 'Scientist', 'Personal Trainer', 'Waiter', 'Judge', 'Clown', 'Architect',
    'Taxi Driver', 'Librarian', 'Baker', 'Pro Gamer', 'News Anchor', 'Spy',
  ] },
  { id: 'sports', name: 'Sports & Hobbies', emoji: '⚽️', words: [
    'Soccer', 'Basketball', 'Tennis', 'Golf', 'Bowling', 'Surfing', 'Skiing', 'Boxing',
    'Yoga', 'Karate', 'Fishing', 'Ice Skating', 'Skateboarding', 'Baseball', 'Swimming', 'Rock Climbing',
    'Archery', 'Gymnastics', 'Volleyball', 'Cycling', 'Chess', 'Ping Pong', 'Hockey', 'Wrestling',
    'Dodgeball', 'Knitting', 'Gardening', 'Painting', 'Karaoke', 'Horse Riding',
  ] },
  { id: 'objects', name: 'Things', emoji: '🪥', words: [
    'Toothbrush', 'Umbrella', 'Toaster', 'Scissors', 'Remote Control', 'Pillow', 'Vacuum Cleaner', 'Mirror',
    'Candle', 'Stapler', 'Sunglasses', 'Backpack', 'Ladder', 'Hairdryer', 'Alarm Clock', 'Frying Pan',
    'Headphones', 'Wallet', 'Microwave', 'Bathtub', 'Guitar', 'Keyboard', 'Lamp', 'Suitcase',
    'Hammer', 'Blender', 'Balloon', 'Tent', 'Doorbell', 'Trampoline', 'Snowman', 'Football Pitch',
  ] },
  { id: 'famous', name: 'Famous People', emoji: '⭐️', words: [
    'Taylor Swift', 'Beyoncé', 'Elon Musk', 'Oprah', 'Shakespeare', 'Albert Einstein', 'Michael Jackson', 'Serena Williams',
    'Lionel Messi', 'Barack Obama', 'Harry Styles', 'Lady Gaga', 'The Rock', 'Mr. Bean', 'Gordon Ramsay', 'Marilyn Monroe',
    'Elvis Presley', 'Santa Claus', 'Napoleon', 'Cleopatra', 'Leonardo da Vinci', 'Tom Cruise', 'Usain Bolt', 'Adele',
    'Mickey Mouse', 'Batman', 'Sherlock Holmes', 'Darth Vader', 'SpongeBob', 'Shrek',
  ] },
  // Phrases, so charades-only (Imposter words must be a single thing).
  { id: 'actions', name: 'Actions', emoji: '🏃', words: [
    'Brushing teeth', 'Walking a dog', 'Riding a rollercoaster', 'Changing a diaper', 'Taking a selfie', 'Doing laundry',
    'Mowing the lawn', 'Parallel parking', 'Blowing up a balloon', 'Milking a cow', 'Proposing', 'Getting a haircut',
    'Playing the drums', 'Walking on ice', 'Eating spaghetti', 'Building a snowman', 'Tying a tie', 'Sneezing',
    'Doing the worm', 'Catching a fish', 'Flipping a pancake', 'Sleepwalking', 'Directing traffic', 'Climbing a ladder',
    'Juggling', 'Skydiving', 'Sword fighting', 'Rowing a boat', 'Stepping on Lego', 'Opening a stuck jar',
  ] },
];

/** Similar-but-different words for Imposter's related-word players, per category. */
export const relatedPairs = {
  animals: [['Dog', 'Wolf'], ['Cat', 'Lion'], ['Horse', 'Zebra'], ['Dolphin', 'Shark'], ['Crocodile', 'Alligator'], ['Rabbit', 'Hamster'], ['Owl', 'Eagle'], ['Frog', 'Toad'], ['Butterfly', 'Moth'], ['Penguin', 'Puffin'], ['Tiger', 'Leopard'], ['Camel', 'Llama'], ['Bee', 'Wasp'], ['Seal', 'Walrus'], ['Gorilla', 'Chimpanzee'], ['Octopus', 'Squid']],
  food: [['Coffee', 'Tea'], ['Burger', 'Sandwich'], ['Pancakes', 'Waffles'], ['Donut', 'Bagel'], ['Butter', 'Margarine'], ['Ketchup', 'Mustard'], ['Muffin', 'Cupcake'], ['Taco', 'Burrito'], ['Wine', 'Champagne'], ['Beer', 'Cider'], ['Croissant', 'Baguette'], ['Lemon', 'Lime'], ['Strawberry', 'Raspberry'], ['Popcorn', 'Crisps'], ['Spaghetti', 'Noodles'], ['Honey', 'Syrup']],
  movies: [['Frozen', 'Tangled'], ['Moana', 'Coco'], ['Titanic', 'Avatar'], ['Alien', 'Predator'], ['Cars', 'Planes'], ['Friends', 'Seinfeld'], ['Rocky', 'Creed'], ['Grease', 'Hairspray'], ['Barbie', 'Oppenheimer'], ['Aladdin', 'Mulan'], ['Twilight', 'Divergent'], ['Jaws', 'Piranha'], ['Shrek', 'Madagascar'], ['Inception', 'Interstellar']],
  places: [['Beach', 'Pool'], ['Hospital', 'Pharmacy'], ['Library', 'Bookshop'], ['Zoo', 'Aquarium'], ['Airport', 'Train Station'], ['Hotel', 'Motel'], ['Church', 'Temple'], ['Gym', 'Spa'], ['School', 'University'], ['Cinema', 'Theatre'], ['Casino', 'Arcade'], ['Castle', 'Palace'], ['Farm', 'Ranch'], ['Supermarket', 'Shopping Centre'], ['Restaurant', 'Cafe'], ['Jungle', 'Forest'], ['Prison', 'Courthouse']],
  jobs: [['Doctor', 'Nurse'], ['Chef', 'Baker'], ['Pilot', 'Astronaut'], ['Teacher', 'Professor'], ['Lawyer', 'Judge'], ['Firefighter', 'Paramedic'], ['Plumber', 'Electrician'], ['Actor', 'Singer'], ['Farmer', 'Gardener'], ['Detective', 'Spy'], ['Dentist', 'Surgeon'], ['Waiter', 'Bartender'], ['Barber', 'Hairdresser'], ['Photographer', 'Painter'], ['Soldier', 'Police Officer']],
  sports: [['Tennis', 'Badminton'], ['Football', 'Rugby'], ['Basketball', 'Netball'], ['Skiing', 'Snowboarding'], ['Surfing', 'Skateboarding'], ['Boxing', 'Wrestling'], ['Baseball', 'Cricket'], ['Hockey', 'Lacrosse'], ['Swimming', 'Diving'], ['Karate', 'Judo'], ['Cycling', 'Running'], ['Chess', 'Draughts'], ['Yoga', 'Pilates'], ['Bowling', 'Darts'], ['Volleyball', 'Handball']],
  objects: [['Pen', 'Pencil'], ['Fork', 'Spoon'], ['Pillow', 'Blanket'], ['Mirror', 'Window'], ['Candle', 'Lamp'], ['Chair', 'Stool'], ['Toaster', 'Microwave'], ['Shampoo', 'Soap'], ['Umbrella', 'Raincoat'], ['Backpack', 'Suitcase'], ['Watch', 'Bracelet'], ['Guitar', 'Violin'], ['Headphones', 'Speaker'], ['Scissors', 'Knife'], ['Hammer', 'Screwdriver'], ['Sunglasses', 'Goggles']],
  famous: [['Beyoncé', 'Rihanna'], ['Lionel Messi', 'Cristiano Ronaldo'], ['Albert Einstein', 'Isaac Newton'], ['Batman', 'Superman'], ['Shakespeare', 'Charles Dickens'], ['Elvis Presley', 'Michael Jackson'], ['Taylor Swift', 'Ariana Grande'], ['Harry Potter', 'Frodo'], ['Mickey Mouse', 'Donald Duck'], ['Santa Claus', 'Easter Bunny'], ['Cleopatra', 'Nefertiti'], ['Napoleon', 'Julius Caesar'], ['Gordon Ramsay', 'Jamie Oliver'], ['Tom Cruise', 'Brad Pitt'], ['Darth Vader', 'Voldemort'], ['Leonardo da Vinci', 'Michelangelo'], ['Sherlock Holmes', 'Hercule Poirot'], ['SpongeBob', 'Patrick Star']],
};

export const spectrums = [
  ['Cold', 'Hot'], ['Underrated', 'Overrated'], ['Useless', 'Useful'], ['Bad movie', 'Good movie'],
  ['Easy to spell', 'Hard to spell'], ['Boring', 'Exciting'], ['Cheap', 'Expensive'], ['Unhealthy', 'Healthy'],
  ['Smells bad', 'Smells good'], ['Normal', 'Weird'], ['Villain', 'Hero'], ['Worst pizza topping', 'Best pizza topping'],
  ['Round', 'Pointy'], ['Soft', 'Hard'], ['Casual', 'Formal'], ['Tiny', 'Huge'],
  ['Forgettable', 'Unforgettable'], ['Sad song', 'Happy song'], ['Mild', 'Spicy'], ['Guilty pleasure', 'Proud to love it'],
  ['Fad', 'Timeless classic'], ['Rare', 'Common'], ['Harmless', 'Dangerous'], ['Uncool', 'Cool'],
  ['Natural', 'Artificial'], ['Underpaid', 'Overpaid'], ['Bad superpower', 'Great superpower'], ['Bad habit', 'Good habit'],
  ['Quiet', 'Loud'], ['Old-fashioned', 'Modern'], ['Temporary', 'Permanent'], ['Introvert activity', 'Extrovert activity'],
  ['Not a sandwich', 'Definitely a sandwich'], ['Terrible gift', 'Perfect gift'], ['Cute', 'Terrifying'], ['Low-calorie', 'High-calorie'],
  ['Useless invention', 'Genius invention'], ['Least fun job', 'Most fun job'], ['Trashy', 'Classy'], ['Easy to do', 'Hard to do'],
  ['Mainstream', 'Niche'], ['For kids', 'For adults'], ['Weak', 'Strong'], ['Sweet', 'Savoury'],
  ['Normal pet', 'Exotic pet'], ['Nerdy', 'Sporty'], ['Bad dog name', 'Great dog name'], ['Morning thing', 'Night thing'],
  ['Fragile', 'Indestructible'], ['Relaxing', 'Stressful'], ['Science', 'Magic'], ['Overdressed', 'Underdressed'],
  ['Unromantic', 'Romantic'], ['Ugly', 'Beautiful'], ['Bad first date', 'Great first date'], ['Wholesome', 'Chaotic'],
  ['Beginner', 'Expert'], ['Short-lived', 'Lives forever'],
];

export const taboo = [
  ['Pizza', ['Cheese', 'Slice', 'Italian', 'Pepperoni', 'Delivery']],
  ['Beach', ['Sand', 'Ocean', 'Sun', 'Waves', 'Swim']],
  ['Birthday', ['Cake', 'Party', 'Candles', 'Present', 'Age']],
  ['Doctor', ['Hospital', 'Sick', 'Nurse', 'Medicine', 'Patient']],
  ['Vampire', ['Blood', 'Dracula', 'Bite', 'Fangs', 'Night']],
  ['Coffee', ['Caffeine', 'Morning', 'Cup', 'Starbucks', 'Bean']],
  ['Football', ['Ball', 'Kick', 'Goal', 'Team', 'Soccer']],
  ['Snowman', ['Winter', 'Carrot', 'Cold', 'Build', 'Frosty']],
  ['Wedding', ['Bride', 'Marry', 'Ring', 'Dress', 'Church']],
  ['Dinosaur', ['Extinct', 'T-Rex', 'Jurassic', 'Fossil', 'Big']],
  ['Netflix', ['Stream', 'Show', 'Binge', 'Movie', 'Watch']],
  ['Guitar', ['Strings', 'Play', 'Music', 'Rock', 'Instrument']],
  ['Airport', ['Plane', 'Fly', 'Gate', 'Security', 'Luggage']],
  ['Pirate', ['Ship', 'Treasure', 'Parrot', 'Eye patch', 'Sea']],
  ['Sunglasses', ['Eyes', 'Sun', 'Shade', 'Wear', 'Cool']],
  ['Selfie', ['Photo', 'Phone', 'Camera', 'Picture', 'Yourself']],
  ['Chocolate', ['Sweet', 'Cocoa', 'Candy', 'Brown', 'Bar']],
  ['Superhero', ['Cape', 'Powers', 'Marvel', 'Save', 'Villain']],
  ['Homework', ['School', 'Teacher', 'Study', 'Assignment', 'Due']],
  ['Volcano', ['Lava', 'Erupt', 'Mountain', 'Hot', 'Ash']],
  ['Alarm Clock', ['Wake', 'Morning', 'Ring', 'Snooze', 'Time']],
  ['Camping', ['Tent', 'Outdoors', 'Fire', 'Sleeping bag', 'Woods']],
  ['Mermaid', ['Fish', 'Tail', 'Sea', 'Ariel', 'Swim']],
  ['Karaoke', ['Sing', 'Microphone', 'Song', 'Bar', 'Lyrics']],
  ['Honeymoon', ['Wedding', 'Trip', 'Married', 'Couple', 'Holiday']],
  ['Ghost', ['Spooky', 'Dead', 'Haunt', 'Sheet', 'Boo']],
  ['Hamburger', ['Beef', 'Bun', "McDonald's", 'Patty', 'Cheese']],
  ['Rainbow', ['Colours', 'Rain', 'Sky', 'Arc', 'Pot of gold']],
  ['Password', ['Login', 'Secret', 'Computer', 'Account', 'Type']],
  ['Zombie', ['Undead', 'Brains', 'Walking', 'Apocalypse', 'Bite']],
  ['Gym', ['Exercise', 'Workout', 'Weights', 'Fitness', 'Treadmill']],
  ['Moon', ['Night', 'Space', 'Sky', 'Full', 'Astronaut']],
  ['Hangover', ['Drunk', 'Headache', 'Alcohol', 'Morning', 'Party']],
  ['Tattoo', ['Ink', 'Needle', 'Skin', 'Design', 'Permanent']],
  ['Emoji', ['Text', 'Smiley', 'Phone', 'Face', 'Icon']],
  ['Lottery', ['Win', 'Money', 'Ticket', 'Numbers', 'Jackpot']],
  ['Penguin', ['Bird', 'Antarctica', 'Ice', 'Waddle', 'Tuxedo']],
  ['Magician', ['Trick', 'Rabbit', 'Hat', 'Wand', 'Disappear']],
  ['Traffic', ['Cars', 'Jam', 'Road', 'Stuck', 'Rush hour']],
  ['Cinderella', ['Slipper', 'Prince', 'Ball', 'Midnight', 'Stepsisters']],
  ['Podcast', ['Listen', 'Episode', 'Audio', 'Host', 'Talk']],
  ['Sushi', ['Fish', 'Rice', 'Japan', 'Raw', 'Roll']],
  ['Lift', ['Floor', 'Up', 'Down', 'Button', 'Elevator']],
  ['Dentist', ['Teeth', 'Filling', 'Drill', 'Floss', 'Mouth']],
  ['Thunderstorm', ['Lightning', 'Rain', 'Loud', 'Weather', 'Cloud']],
  ['Influencer', ['Instagram', 'Followers', 'Social media', 'Post', 'Famous']],
  ['Bubble Bath', ['Soap', 'Tub', 'Relax', 'Foam', 'Water']],
  ['Rollercoaster', ['Ride', 'Theme park', 'Loop', 'Scream', 'Fast']],
  ['Grandma', ['Old', 'Family', 'Mother', 'Cookies', 'Knit']],
  ['Wi-Fi', ['Internet', 'Password', 'Connect', 'Router', 'Signal']],
];

export const bombCategories = [
  'A pizza topping', 'A country', 'A Disney movie', 'A dog breed', 'A car brand', 'Something in a kitchen',
  'A sport', 'A fruit', 'A vegetable', 'A board game', 'A TV show', 'A singer or band',
  'A cartoon character', 'A body part', 'A capital city', 'Something you pack for a holiday', 'A type of cheese',
  'An ice cream flavour', 'A superhero', 'A job', 'A musical instrument', 'Something cold', 'A breakfast food',
  'A colour', 'A famous athlete', 'A fast food chain', 'A Harry Potter character', 'A clothing brand',
  'Something in a bathroom', 'A flower', 'An app on your phone', 'A holiday', 'Something that flies',
  'A sea creature', 'A chocolate bar or sweet', 'A cocktail', 'Something round', 'A Pixar movie',
  'A dance', 'Something with wheels', 'A school subject', 'A dessert', 'A famous landmark',
  'A language', 'A video game', 'A bird', 'Something sticky', 'A Beatles song', 'A word that rhymes with CAT',
  "Something you'd find in a garden", 'A reality TV show', 'A pasta shape', 'A spice or herb',
];

export const bombLetters = [
  'ING', 'ER', 'TH', 'OU', 'AR', 'EA', 'ST', 'CH', 'SH', 'IGHT',
  'TION', 'PL', 'BR', 'OO', 'EE', 'AN', 'IN', 'ON', 'UM', 'OW',
  'ACK', 'ELL', 'UNK', 'OCK', 'AB', 'GR', 'FL', 'SP', 'QU', 'X',
  'Z', 'MP', 'IVE', 'ARD', 'EST', 'OLD', 'AMP', 'IP', 'UG', 'NK',
];

export const decks = {
  mostLikely: {
    name: 'Most Likely To', emoji: '👉', header: "Who's most likely to…",
    how: 'On three, everyone points. Most fingers has to explain themselves.',
    prompts: [
      'Become famous', 'Survive a zombie apocalypse', "Cry at a kids' movie", 'Forget their own birthday',
      'Become a millionaire', 'Get lost in their own city', 'Win a reality TV show', 'Adopt ten cats',
      'Text their ex tonight', 'Laugh at a funeral', 'Go viral for something embarrassing', 'Still be up at 4am',
      'Start a cult', 'Get arrested', 'Eat something off the floor', 'Talk their way out of a speeding ticket',
      'Move abroad on a whim', 'Be late to their own wedding', 'Binge a whole series in a day', 'Fall asleep at a party',
      'Have a secret talent', 'Become a politician', 'Get a tattoo they regret', 'Grab the karaoke mic first',
      'Lose their phone tonight', 'Befriend a stranger on a plane', 'Run a marathon', 'Eat the last slice without asking',
      'Get scammed online', 'Plan the group trip', 'Ghost someone', 'Believe a conspiracy theory',
      'Go skydiving', 'Write a bestselling book', 'Cheat at board games', 'Marry a celebrity',
      'Survive alone in the wild', 'Accidentally reply-all', 'Show up in pyjamas', 'Start a business that actually works',
    ],
  },
  wouldYouRather: {
    name: 'Would You Rather', emoji: '🤔', header: 'Would you rather…',
    how: 'Everyone picks a side. The minority has to defend their choice.',
    prompts: [
      'Be able to fly, or be invisible?', 'Always be 10 minutes late, or always 20 minutes early?',
      'Give up music, or give up movies?', 'Live without the internet, or without heating?',
      'Have a rewind button, or a pause button for your life?', 'Be the funniest person in the room, or the smartest?',
      'Only eat pizza forever, or never eat pizza again?', 'Know how you die, or when you die?',
      'Talk to animals, or speak every human language?', 'Have unlimited money, or unlimited free time?',
      'Fight one horse-sized duck, or 100 duck-sized horses?', 'Be famous but broke, or rich but unknown?',
      'Never be able to lie, or never know when others are lying?', 'Live in the city, or the countryside forever?',
      'Sing instead of talk, or dance everywhere you walk?', 'Lose your phone, or your wallet?',
      'Go back in time, or into the future?', 'Have hiccups forever, or always feel about to sneeze?',
      'Read minds, or see the future?', 'Be stranded on an island alone, or with someone you hate?',
      'Sweat mayonnaise, or cry maple syrup?', 'Have a personal chef, or a personal driver?',
      'Only whisper, or only shout?', 'Relive the same day forever, or skip a year every day?',
      'Give up coffee, or give up alcohol?', 'Be a famous athlete, or a famous musician?',
      'Have no eyebrows, or one giant unibrow?', 'Never use social media again, or never watch TV again?',
      'Explore space, or the deep ocean?', 'Have a pet dinosaur, or a pet dragon?',
      'Share every thought out loud, or never speak again?', 'Eat a live bug, or a spoonful of wasabi?',
      'Never be cold, or never be hot?', 'Be in a horror movie, or a musical?',
    ],
  },
  hotTakes: {
    name: 'Hot Takes', emoji: '🌶️', header: 'Agree or disagree?',
    how: 'Thumbs up or down on three. Then fight it out.',
    prompts: [
      'Pineapple belongs on pizza.', 'Cats are better than dogs.', 'Breakfast is overrated.',
      'The book is always better than the movie.', 'Cereal is a soup.', 'Sequels are usually better.',
      'Beach holidays are boring.', "It's fine to recline your plane seat.", 'Tipping culture has gone too far.',
      'Weddings should be under 50 people.', 'A hot dog is a sandwich.', 'The gym is overrated.',
      'Texting is better than calling.', 'Christmas music in November is fine.', 'Being early is rude.',
      'Reality TV is actually great.', 'Socks with sandals are acceptable.', 'Water is wet.',
      'Shower in the morning, not at night.', 'Board games beat video games.',
      'Brunch is a scam.', "It's okay to leave a party without saying goodbye.", 'Coriander tastes like soap.',
      "Mondays aren't that bad.", 'Road trips beat flying.', 'Ketchup goes in the fridge.',
      'Karaoke is the best night out.', 'Summer is the worst season.', 'Remakes are never as good.',
      'Double-dipping is fine among friends.',
    ],
  },
  neverHaveI: {
    name: 'Never Have I Ever', emoji: '🙈', header: 'Never have I ever…',
    how: "Put a finger down if you have. Storytime is mandatory.",
    prompts: [
      'Pretended to be sick to skip something', 'Stalked an ex online', 'Sent a text to the wrong person',
      'Fallen asleep in public', 'Lied about my age', 'Re-gifted a present', 'Walked into a glass door',
      'Sung loudly enough in the shower for the neighbours to hear', 'Cried at an advert', 'Got lost with GPS on',
      'Eaten food that fell on the floor', 'Laughed so hard I snorted', "Forgotten someone's name mid-conversation",
      'Pretended to know a song', 'Been kicked out of somewhere', 'Binged a full season in one day',
      "Said 'you too' when a waiter said enjoy your meal", "Waved back at someone who wasn't waving at me",
      'Googled myself', 'Lied on my CV', 'Had a crush on a teacher', 'Broken something and hidden it',
      'Missed a flight', 'Talked to myself in the mirror', "Faked laughing at a joke I didn't get",
      'Snuck food into a cinema', 'Tripped over nothing', "Used someone else's Netflix",
      'Stayed up all night', "Read someone's texts over their shoulder",
    ],
  },
};
